version: "3.9"

services:
  mysql-media:
    image: mysql:8.0
    container_name: mysql-media
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: media_db
      MYSQL_USER: media
      MYSQL_PASSWORD: media123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  media-backend:
    image: media-backend-media-backend
    container_name: media-backend
    depends_on:
      - mysql-media
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-media:3306/media_db
      SPRING_DATASOURCE_USERNAME: media
      SPRING_DATASOURCE_PASSWORD: media123

volumes:
  mysql_data:
