services:
  mysql-media:
    image: mysql:8.0
    container_name: mysql-media
    restart: always
    environment:
      MYSQL_DATABASE: media_db
      MYSQL_USER: media
      MYSQL_PASSWORD: media123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  media-backend:
    build: .
    container_name: media-backend
    depends_on:
      mysql-media:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-media:3307/media_db
      SPRING_DATASOURCE_USERNAME: media
      SPRING_DATASOURCE_PASSWORD: media123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
